[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from   = "/app/*"
  to     = "https://fanciful-queijadas-0b6505.netlify.app/app/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200